config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :products

      root to: "users#index"
    end
   
   get 'thankyou', to: 'products#index'
  root to: 'visitors#index'
   resources :products 
   
   devise_for :users
   resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
 
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
 has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :user
before_save :subtotal
before_save :defbalance

 def subtotal 
  pricetotal = quantity * price
  self.total = pricetotal
 end

 def defbalance 
  balancesum = (price * quantity) - paid 
  self.balance = balancesum
 end	
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:client, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :client
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :products
        
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end
      # TODO Add authentication logic here.
    

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    thankyou_path
  end

  def after_sign_out_path_for(resource)
    thankyou_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :authenticate_user!
 
 
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @products = Product.where(user: current_user) 
    
  end



  # GET /items/1
  # GET /items/1.json
  def show

  end

  # GET /items/new
  def new
    @product = Product.new(:user_id => @current_user)
  end

  # GET /items/1/edit
  def edit
    current_user.products.build
  end

  # POST /items
  # POST /items.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
   
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        current_user.products.build
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :description, :name, :status, :quantity, :price, :total, :paid, :balance, :user_id)
    end
end

app/controllers/thank_you_controller.rb
class ThankYouController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "Client updated."
    else
      redirect_to users_path, :alert => "Unable to update Client."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "Client deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role, :name)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
 
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SignIn Thankyou" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Signup Thankyou" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application',  'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
 
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    

       <%= render 'layouts/messages' %>
       <%= yield %>

  </div>
  </body>
</html>

app/views/pages/about.html.erb
<main role="main">
<% content_for :title do %>About<% end %>

<h3>About the Website</h3>
<div class="container">
<p>
This web application is for you to place orders and to check if delivery and payments have been made...</p>
</div>
</main>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div id="productn">
 <div id="product" class="field">
    <%= form.label :name %>
    <%= form.select(:name, options_for_select([['Take-Away Serviettes(E155)','Take-Away Serviettes'],['Everyday Serviettes(E95)','Everyday Serviettes'],['House-Hold Towels(E16)','House-Hold Towels']]), :prompt => "Choose your product") %>
  </div>
  
<div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity,:value => 1 %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%= form.select(:status, options_for_select([['PENDING','PENDING'],['DELIVERED','DELIVERED'],['PAID','PAID']])) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.select(:price, options_for_select([['E155','155'],['E95','95'],['E16','16']])) %>
  </div>

  <div class="field">
  
    <%= form.hidden_field :total %>
  </div>

  <div class="field">
   
    <%= form.hidden_field :paid %>
  </div>

  <div class="field">
  
    <%= form.hidden_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<main role="main">

<h1>Your Orders: <%= current_user.products.count %></h1>



<table id="myTable" class='table table-striped table-dark'>
  <thead>
    <tr>
       <th scope="col">Order Date:</th>
  
      <th scope="col">Status</th>
          
      <th scope="col">Balance</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <div class="pull-right"><%= link_to 'New', new_product_path, :class => 'btn-primary button-xs' %></div>
    
    
    <% @products.each do |product| %>
      <tr>
        <td scope="row"><%= product.created_at.strftime("%d-%b-%Y") %></td>
      
        <td scope="row"><%= product.status %></td>
     
           
        <td scope="row"><font color="red"><strong><%= number_to_currency(product.defbalance, :unit => "E", :separator => ".", :delimiter => ",") %></font></strong></td>


        <td><%= link_to 'Show', product, :class => 'btn-success button-xs' %></td>
        
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_product_path(product), :class => 'btn-primary button-xs' %></td>
        <td><%= link_to 'Destroy', product, method: :delete, :class => 'btn-danger button-xs', data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>


</main>

app/views/products/new.html.erb
<main role="main">
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</main>

app/views/products/show.html.erb
<main role="main">

<form>
<br />


<div class="form-group">
  Description:<strong>  <%= @product.name %> </strong>
</div>


<div class="form-group">
  Quantity:
  <%= @product.quantity %>
</div>

<div class="form-group">
  Status:
  <%= @product.status %>
</div>

<div class="form-group">
  Price:
  <%= number_to_currency(@product.price,:unit => "E", :separator => ".", :delimiter => ",") %></font>
</div>

<div class="form-group">
  Total: <font color="red"><%= number_to_currency(@product.subtotal,:unit => "E", :separator => ".", :delimiter => ",") %></font>
</div>

<div class="form-group">
  Paid: <font color="green"><%= number_to_currency(@product.paid,:unit => "E", :separator => ".", :delimiter => ",") %></font>
  
 
</div>

<div class="form-group">
    Balance: <font color="red"><strong><%= number_to_currency(@product.defbalance,:unit => "E", :separator => ".", :delimiter => ",") %></font></strong>
 
  
</div>


<%= link_to 'Back', products_path, class: 'btn-primary btn-sm' %>
</div>
</form>
</main>

app/views/thank_you/index.html.erb
<main role="main">

<h3>Welcome...</h3>
<% if user_signed_in? %>
  <h3>You've signed up...</h3>
  
  <%= link_to 'Products', products_path, class: 'btn btn-success btn-large' %>
<% else %>
  <h3>Sign up to view and place orders.</h3>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-large' %>
<% end %>
</main>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user, :class => 'btn-success button-xs' %>
</td>
<td>

  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>

  <% end %>

  </td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn-danger button-xs') unless user == current_user %>
  </td>

app/views/users/index.html.erb
<main role="main">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
         
         
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</main>

app/views/users/show.html.erb
<main role="main">
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>


<%= link_to 'Products', admin_users_path, class: 'btn btn-success btn-large' %>
</main>

app/views/visitors/index.html.erb
<main role="main">
<h3>Welcome </h3>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %>  
     ||  <%= link_to 'Admin Page', admin_users_path, class: 'btn btn-success btn-default' %></p>
  <% else %>
    <h3>You've signed up. <%= link_to 'Products', thankyou_path %></h3>
  <% end %>
<% else %>
  <h3>Welcoming all our clients please Sign in and place your orders as well as view the status of orders..</h3>
  <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary btn-large' %>
<% end %>
</main>